name: assignment2
on: [push, pull_request]

defaults:
  run:
    working-directory: assignment2/

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.6

      - name: Install dependencies
        run: poetry install --no-root

      - name: Lint
        run: |
          poetry run python -m pylint libs/ ./*.py
          poetry run python -m mypy libs/ ./*.py

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.6

      - name: Install dependencies
        run: poetry install --no-root

      - name: Test
        run: poetry run python -m pytest tests/

  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.6

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run scripts
        run: |
          poetry run python preprocess.py dating-full.csv dating.csv
          poetry run python 2_1.py dating.csv
          poetry run python 2_2.py dating.csv
          poetry run python discretize.py dating.csv dating-binned.csv
          poetry run python split.py dating-binned.csv trainingSet.csv testSet.csv
          poetry run python 5_1.py
          poetry run python 5_2.py
          poetry run python 5_3.py
