name: assignment2
on: [push, pull_request]

defaults:
  run:
    working-directory: assignment2/

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.6

      - name: Install dependencies
        run: poetry install --no-root

      - name: Lint
        run: |
          poetry run python -m pylint naive_bayes_classifier/
          poetry run python -m mypy naive_bayes_classifier/

  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.6

      - name: Install dependencies
        run: poetry install --no-root

      - name: Test
        run: poetry run python -m pytest tests/

  run:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.6

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run scripts
        run: |
          poetry run python preprocess.py
          poetry run python 2_1.py
          poetry run python 2_2.py
          poetry run python discretize.py
          poetry run python split.py
          poetry run python 5_1.py
          poetry run python 5_2.py
          poetry run python 5_3.py
