name: build
on: [push, pull_request]

jobs:
  assignment2-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: assignment2/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.6

      - name: Install dependencies
        run: poetry install --no-root

      - name: Lint
        run: |
          poetry run python -m pylint naive_bayes_classifier/
          poetry run python -m mypy naive_bayes_classifier/

  assignment2-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: assignment2/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.6

      - name: Install dependencies
        run: poetry install --no-root

      - name: Test
        run: poetry run python -m pytest tests/
